### PR TITLE
Allow screen tap to close menu

### LINKED ISSUE #53: Disable onDrag but keep onTap to close menu
When I add `onDrag: false`, I can't close menu by tapping on screen anymore. I'll create a PR fixing this. :-)

### PR DESCRIPTION
**Pull request by HugoHeneault**
Close #53

### CODE REVIEW

**Comment by HugoHeneault** [comment]
I just realized that I broke something. Please hold it while I fix it. 😕

**Comment by HugoHeneault** [comment]
Here I should have fixed it :-)

**Comment by RafaelBarbosatec** [comment]
Hi @HugoHeneault !
Thanks for contributing !

**Comment by harish-rohokale-apptware** [comment]
Allow screen tap to close menu ,what if i don't want it how do i set it not to open?

**Pull request merged**
